QESRC_DIR = external/mbd/src
PNAME = qepy_mbd
QEPY_LIBS = -L$(BUILDDIR) 
QEPY_INCS = -I. -I$(QEDIR)/$(QESRC_DIR) 

QEPY_OBJS = 

QEPY_PROG_OBJS = 

QE_OBJS = 

LIB_OBJS_TEMP = mbd.o \
mbd_c_api.o \
mbd_constants.o \
mbd_coulomb.o \
mbd_damping.o \
mbd_dipole.o \
mbd_formulas.o \
mbd_geom.o \
mbd_gradients.o \
mbd_hamiltonian.o \
mbd_lapack.o \
mbd_linalg.o \
mbd_matrix.o \
mbd_methods.o \
mbd_rpa.o \
mbd_scs.o \
mbd_ts.o \
mbd_utils.o \
mbd_vdw_param.o

include ../make.qepy.inc
include ../make.depend
