QESRC_DIR = UtilXlib
PNAME = qepy_utilxlib
QEPY_LIBS = -L$(BUILDDIR) 
QEPY_INCS = -I. -I$(QEDIR)/$(QESRC_DIR) 

QEPY_OBJS = 

QEPY_PROG_OBJS = 

QE_OBJS = 

LIB_OBJS_TEMP = c_mkdir.o \
clib_wrappers.o \
clocks_handler.o \
copy.o \
cptimer.o \
data_buffer.o \
device_helper.o \
divide.o \
error_handler.o \
eval_infix.o \
export_gstart_2_solvers.o \
find_free_unit.o \
fletcher32.o \
fletcher32_mod.o \
md5.o \
md5_from_file.o \
mem_counter.o \
memstat.o \
memusage.o \
mp.o \
mp_bands_util.o \
mp_base.o \
mp_base_gpu.o \
nvtx_wrapper.o \
parallel_include.o \
print_mem.o \
ptrace.o \
set_mpi_comm_4_solvers.o \
thread_util.o \
util_param.o

include ../make.qepy.inc
include ../make.depend
