name: Build wheels on Linux

on:
  push:
    branches:
      - action
  pull_request:
    branches:
      - action

jobs:
  build_wheels_linux:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-20.04, manylinux, x86_64]
        python: ["cp37"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Build wheels on linux
        if: ${{ matrix.buildplat[1] == 'manylinux' }}
        uses: pypa/cibuildwheel@v2.12.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}*
          CIBW_ENVIRONMENT: FFLAGS='-fPIC -fallow-argument-mismatch' oldxml=yes SETUPTOOLS_USE_DISTUTILS=stdlib QE_INSTALL_FLAGS='--enable-openmp=yes'
          CIBW_ENVIRONMENT_PASS_LINUX: FFLAGS oldxml SETUPTOOLS_USE_DISTUTILS QE_INSTALL_FLAGS
          CIBW_ARCHS_LINUX: "auto"
          CIBW_BEFORE_BUILD: |
            yum install -y blas-devel lapack-devel fftw-devel

      - uses: actions/upload-artifact@v3
        with:
          name: qepy-wheels
          path: ./wheelhouse/*.whl
