QESRC_DIR = XClib
PNAME = qepy_xclib
QEPY_LIBS = -L$(BUILDDIR) -lqepy_upflib
QEPY_INCS = -I. -I$(QEDIR)/$(QESRC_DIR) -I$(BUILDDIR)/upflib -I$(QEDIR)/upflib

QEPY_OBJS = 

QEPY_PROG_OBJS = 

QE_OBJS = dft_setting_routines.o

LIB_OBJS_TEMP = beefun.o \
dft_setting_params.o \
dft_setting_routines.o \
pbecor.o \
qe_constants.o \
qe_dft_list.o \
qe_drivers_d_gga.o \
qe_drivers_d_lda_lsda.o \
qe_drivers_gga.o \
qe_drivers_lda_lsda.o \
qe_drivers_mgga.o \
qe_funct_corr_gga.o \
qe_funct_corr_lda_lsda.o \
qe_funct_exch_gga.o \
qe_funct_exch_lda_lsda.o \
qe_funct_mgga.o \
qe_kind.o \
xc_beef_interface.o \
xc_lib.o \
xc_wrapper_d_gga.o \
xc_wrapper_d_lda_lsda.o \
xc_wrapper_gga.o \
xc_wrapper_lda_lsda.o \
xc_wrapper_mgga.o \
xclib_error.o \
xclib_utils_and_para.o

include ../make.qepy.inc
include ../make.depend
